name: flutter_bloc_base
description: An advanced Flutter boilerplate with BLoC and feature-first architecture.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  hydrated_bloc: ^10.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  auto_route: ^10.1.0+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  logger: ^2.6.0
  path_provider: ^2.1.5
  auto_route_generator: ^10.2.3
  flutter_dotenv: ^5.2.1
  internet_connection_checker_plus: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.4
  freezed: ^2.4.7
  json_serializable: ^6.6.2
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - .env
