name: flutter_bloc_base
description: An advanced Flutter boilerplate with BLoC and feature-first architecture.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3          # BLoC state management
  bloc: ^8.1.2                 # Core BLoC utilities
  equatable: ^2.0.5            # Simplifies equality comparisons
  hydrated_bloc: ^9.0.0        # Persists BLoC state
  get_it: ^7.6.4               # Dependency injection
  dio: ^5.3.2                  # HTTP client
  connectivity_plus: ^4.0.2     # Network connectivity
  auto_route: ^7.8.0           # Navigation
  flutter_localizations: # Localization
    sdk: flutter
  intl: ^0.20.2                # Internationalization (Updated)
  freezed_annotation: ^2.4.1    # Immutable data classes
  json_annotation: ^4.8.1       # JSON serialization
  shared_preferences: ^2.2.2    # Local storage
  logger: ^2.0.2               # Logging
  path_provider: ^2.1.1        # File system paths
  auto_route_generator: ^7.3.2 # Ensure this is present

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4            # BLoC testing
  mockito: ^5.4.2              # Mocking
  build_runner: ^2.4.6         # Code generation
  freezed: ^2.4.1              # Freezed generator
  json_serializable: ^6.7.1     # JSON serialization generator
  very_good_analysis: ^5.1.0    # Linting